### ISSUE TITLE
All submissions cause an error (including AutoML competition)

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1049]
There is a problem with parsing the submission, the error is as follows (the same when some files are missing in the .zip)

Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 219, in run
    bundles = getBundle(root_dir, blob_service, container, run_id, 'run')
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 144, in getBundle
    return getThem(bundle_id, bundle_rel_path, {}, 0)
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 140, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 140, in getThem
    getThem(v, join(bundle_rel_path, k), bundles, depth + 1)
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 137, in getThem
    for (k, v) in bundle_info.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by lr292358** [comment]
It's ok now so I close it
