### ISSUE TITLE
cl wedit on codalab.org results in error

### ISSUE THREAD

**Issue by tonyyang1993** [codalab/codalab#1303]
`cl wedit` on various worksheet on www.codalab.org and got the same error: `xmlrpclib.Fault: <Fault 1: '<type \'exceptions.Exception\'>:method "update_worksheet" is not supported'>`

Stack trace back:
```
Traceback (most recent call last):
  File "/root/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/root/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/root/codalab-cli/codalab/lib/bundle_cli.py", line 357, in do_command
    command_fn(remaining_args, parser)
  File "/root/codalab-cli/codalab/lib/bundle_cli.py", line 1259, in do_wedit_command
    client.update_worksheet(worksheet_info, new_items)
  File "/root/codalab-cli/codalab/client/remote_bundle_client.py", line 139, in inner
    return getattr(self.proxy, command)(*args, **kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: '<type \'exceptions.Exception\'>:method "update_worksheet" is not supported'>
```

**Comment by tonyyang1993** [comment]
The bug can be reproduced by 

1. `cl new` a new worksheet
2. `cl wedit`
3. make some modification
4. `:wq`

**Comment by percyliang** [comment]
Do a git pull and see if that helps

**Comment by tonyyang1993** [comment]
The error mentioned above is on codalab.org server.

For local test, after `git pull` master branch of both `codalab` and `codalab-cli`, got different error as follows:

```
ty@ubuntu:~$ cl wedit
Traceback (most recent call last):
  File "/home/ty/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 66, in <module>
    run_cli()
  File "/home/ty/codalab-cli/codalab/bin/../../codalab/bin/cl.py", line 57, in run_cli
    cli.do_command(sys.argv[1:])
  File "/home/ty/codalab-cli/codalab/lib/bundle_cli.py", line 359, in do_command
    command_fn(remaining_args, parser)
  File "/home/ty/codalab-cli/codalab/lib/bundle_cli.py", line 1252, in do_wedit_command
    client, worksheet_uuid = self.parse_client_worksheet_uuid(args.worksheet_spec)
  File "/home/ty/codalab-cli/codalab/lib/bundle_cli.py", line 304, in parse_client_worksheet_uuid
    client, worksheet_uuid = self.manager.get_current_worksheet_uuid()
  File "/home/ty/codalab-cli/codalab/lib/codalab_manager.py", line 355, in get_current_worksheet_uuid
    worksheet_uuid = client.get_worksheet_uuid(None, '')
  File "/home/ty/codalab-cli/codalab/client/local_bundle_client.py", line 135, in get_worksheet_uuid
    return canonicalize.get_worksheet_uuid(self.model, base_worksheet_uuid, worksheet_spec)
  File "/home/ty/codalab-cli/codalab/lib/canonicalize.py", line 126, in get_worksheet_uuid
    worksheets = model.batch_get_worksheets(fetch_items=False, name=worksheet_spec, base_worksheet_uuid=base_worksheet_uuid)
  File "/home/ty/codalab-cli/codalab/model/bundle_model.py", line 691, in batch_get_worksheets
    cl_worksheet.select().distinct().where(clause)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1987, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/ty/codalab-cli/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: worksheet.title [SQL: u'SELECT DISTINCT worksheet.id, worksheet.uuid, worksheet.name, worksheet.owner_id, worksheet.title, worksheet.frozen \nFROM worksheet \nWHERE worksheet.name = ?'] [parameters: ('codalab',)]
```

However, the up-to-date `codalab` works well with a month old `codalab-cli`. Maybe the error is introduced by some recent change on `codalab-cli`.

**Comment by percyliang** [comment]
Right, the database schema changed and sqlite doesn't support migrations
properly.

The easiest fix: if you don't care about blowing away your local bundles
data, then just delete .codalab/bundle.db (along with .codalab/data) and
then try again.

 -Percy

**Comment by tonyyang1993** [comment]
Great! Now it is working well locally, including `cl wedit`. Maybe update the source code on the server will solve the original issue.

**Comment by percyliang** [comment]
Will be resolved when we have sane defaults.
