### ISSUE TITLE
`cl help wperm` in action bar gives INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab#1333]
![screen shot 2015-10-11 at 8 31 50 pm](https://cloud.githubusercontent.com/assets/614837/10421153/2d6f41dc-7057-11e5-9c54-659634865c8b.png)

**Comment by kashizui** [comment]
Error on server side looks like:

```
ERROR:root:<apps.api.views.worksheet_views.WorksheetsCommandApi object at 0x107e33410>
ERROR:root:local variable 'structured_result' referenced before assignment
ERROR:root:
ERROR:root:-------------------------
ERROR:root:Traceback (most recent call last):
  File "/Users/sckoo/Developer/codalab/codalab/apps/api/views/worksheet_views.py", line 294, in post
    data = service.general_command(data['worksheet_uuid'], data['command'])
  File "/Users/sckoo/Developer/codalab/codalab/apps/web/bundles.py", line 292, in general_command
    return _call_with_retries(do_command)
  File "/Users/sckoo/Developer/codalab/codalab/apps/web/bundles.py", line 39, in _call_with_retries
    return f()
  File "/Users/sckoo/Developer/codalab/codalab/apps/web/bundles.py", line 291, in do_command
    return {'structured_result': structured_result, 'stdout': stdout_str, 'stderr': stderr_str, 'exception': str(exception) if exception else None}
UnboundLocalError: local variable 'structured_result' referenced before assignment
```

**Comment by kashizui** [comment]
Might be related to @pbhatnagar3's new variable?

**Comment by percyliang** [comment]
I actually fixed this along the way in
https://github.com/codalab/codalab/pull/1332

**Comment by kashizui** [comment]
Oh perfect! Sorry for extra issue.
